nombre=input('What is your name:')
producto1=input('Product name:')
precio1=int(input('Price of the object:'))
producto2=input('Product name:')
precio2=int(input('Price of the object:'))
producto3=input('Product name:')
precio3=int(input('Price of the object:'))
producto4=input('Product name:')
precio4=int(input('Price of the object:'))
producto5=input('Product name:') 
precio5=int(input('Price of the object:'))
print('')
print('TICKET')
print('Your name is:',nombre)
print('Your products are: ',producto1,producto2,producto3,producto4,producto5)
Suma=(precio1+precio2+precio3+precio4+precio5)
print('Price without IVA: ',Suma)
Subtotal=((precio1+precio2+precio3+precio4+precio5)*0.16)
print('IVA: ',Subtotal)
print('Your total price is: ',Suma+Subtotal)
